---
abstract: 'Retrieve infromation from SourceForge site'
author:
  - 'Kang-min Liu (gugod@gugod.org)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-SourceForge
no_index:
  directory:
    - t
    - inc
requires:
  HTML::TableExtract: 0
  WWW::Mechanize: 0
  YAML: 0
version: 0.10
