---
abstract: "Interface to SourceForge's APIs - http://sourceforge.net/p/forge/documentation/API/"
author:
  - 'Rich Bowen (rbowen@sourceforge.net)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-SourceForge
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 0
  JSON::Parse: 0
  LWP::Simple: 0
  Test::More: 0
  Test::Simple: 0.44
  XML::Feed: 0
version: 0.40
